### ISSUE TITLE
Custom Dataset Error

### ISSUE THREAD

**Issue by Iceofsky** [dorarad/gansformer#13]
Hi! 
Thank you for the amazing work!

I encountered a problem when preparing a custom dataset from a custom directory.

```Traceback (most recent call last):
  File "prepare_data.py", line 211, in <module>
    run_cmdline(sys.argv)
  File "prepare_data.py", line 208, in run_cmdline
    prepare(**vars(args))
  File "prepare_data.py", line 156, in prepare
    print(misc.bold("Preparing the {} dataset...".format(c.name)))
AttributeError: 'dict' object has no attribute 'name'
```

I've followed the instruction in using the following commands, replacing the default values with my own values:

```python prepare_data.py --task <dataset-name> --images-dir <source-dir> --format png --ratio 0.7 --shards-num 5```

However, it seems that there is no name attribute in this command and the dictionary passed by specifying a custom task name lacks some keys.

Any tips will be helpful!

**Comment by profour** [comment]
I ran into this same issue. I was able to fix it by wrapping a raw dict with "EasyDict" in prepare_data.py [here](https://github.com/dorarad/gansformer/blob/main/prepare_data.py#L144).

`        c = catalog.get(task, EasyDict({
            "local": True,
            "name": task,
            "dir": images_dir,
            "ratio": ratio,
            "process": formats_catalog.get(format)
        }))
`

**Comment by Iceofsky** [comment]
Thank you! That solved the issue!

**Comment by dorarad** [comment]
Will make sure to incorporate the changes into the codebase so that there will be no need for a workaround!

**Comment by dorarad** [comment]
Alright added in those changes to the repository, thanks @profour !
