### ISSUE TITLE
`maps_in` in the graph?

### ISSUE THREAD

**Issue by Susmit-A** [dorarad/gansformer#21]
Hi,

I'm trying to extract some intermediate values from the model. The graph requires 3 inputs, as listed by `Gs.list_layers()` and `Gs.input_names`:

```
('latents_in', <tf.Tensor 'Gs/latents_in:0' shape=(?, 17, 32) dtype=float32>, [])
('labels_in', <tf.Tensor 'Gs/labels_in:0' shape=(?, 0) dtype=float32>, [])
('maps_in', <tf.Tensor 'Gs/maps_in:0' shape=(?, 16, 256, 256) dtype=float32>, [])
```

`latents_in` is the sampled `z` vector, and it appears `labels_in` is not required (the last dimension is 0). However, I'm not able to understand what `maps_in` is. How can I get `maps_in`?

**Comment by dorarad** [comment]
Hi, Thank you for the interest in the work! 
I have couple deadlines over the next days so will definitely try to get back to you by the end of the week!

**Comment by dorarad** [comment]
Hi, apologies for the large delay in my response and thanks so much for raising that point! 
`maps_in` refers to a unused remnant that stayed in the pickle and doesn't impact the model's behavior. I recommend loading the model using --recompile and then it should save a new snapshot that doesn't have the field. I will also update the checkpoints to not include that unnecessary field!

**Comment by dorarad** [comment]
Just thought to update I updated the pretrained networks files to match the source code so maps_in doesn't appear anymore!
