### ISSUE TITLE
Pretrained Stylegan v2 Model on clevr and cityscapes dataset

### ISSUE THREAD

**Issue by kris-singh** [dorarad/gansformer#31]
Hi Drew,
I tried reaching out via email. 
Is it possible to release the StyleGAN v2 pre-trained weights for clver and cityscapes datasets? 
You use these models as your baseline for the GANsformer model but I had trouble replicating StyleGAN v2 fid scored on these models 

Thanks,
Krish

**Comment by dorarad** [comment]
Hi Krish, Thank you for your message! I currently don't plan to release the pretrained checkpoints for the varied baselines but note that they all are supported and can be trained by the implementation in the repo! (although I understand that would require the GPUs etc). I'll definitely let you know if I release additional checkpoints!
