### ISSUE TITLE
Projecting to the latent space experiment

### ISSUE THREAD

**Issue by jjparkcv** [dorarad/gansformer#4]
Dear authors, 

Thank you sharing code for the amazing work!

I wonder if you have tried finding a set of latent codes for a given image (i.e. latent space projection)?

Would be great to see how it should work!

**Comment by dorarad** [comment]
Hi, Thanks a lot for the kind words! :)
Yea I'm currently looking exactly into it, but no released yet. I plan to extend the model further over the next weeks and months, will make sure to update the readme with any new feature that will be added!
